# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

templates:
  params:
    author-email: samboosalis@gmail.com
    author-name: Spiros Boosalis
    github-username: sboosali
    copyright: 2016 Spiros Boosalis
    module: TODO 
